### ISSUE TITLE
Docker images are outdated

### ISSUE THREAD

**Issue by raphaeljolivet** [decidim/docker#37]
Hi, 

I see that the docker images here are quite outdated (2 months ago):
https://hub.docker.com/r/decidim/decidim/tags/

I would like to run a the last stable release of Decidim (0.14.3) with docker-compose.
I am not sure not understand what part is taken from my local git repository and what part is taken from the root docker image.

Should I build a base docker image locally and use it in docker-compose ? 
Or is it ok to run a recent (0.14.3) decidim app on a quite old (:latest) docker image ?

Thanks for your help.

**Comment by mrcasals** [comment]
Hi @raphaeljolivet! Let me ping @josepjaume here, since he's been the one working on this repo 😄

**Comment by oriolgual** [comment]
Hi @raphaeljolivet, sorry for the delay. I've pushed the images for Decidim 0.14.4 and Decidim 0.13.1 using Ruby 2.5.3.
