### ISSUE TITLE
Execute an instance

### ISSUE THREAD

**Issue by uribes78** [decidim/docker#39]
I've downloaded Dockerfile's and build de main image (Dockerfile), everything went fine, but I trying to run the app to test it an validate it, but it just install the dependencies, finish, then nothing else happend.

the command I'm running is:

`sudo docker run --name decidim-demo ba3153 demo`

but as I said, just create the app but it does'nt run it to test it from browser. Maybe is a dummy question, but we need to test decidim first. Hoping you can help me to know how to set it to run. 

Thanks

**Comment by oliverbarnes** [comment]
Hi @uribes78 many apologies for the two-year delay :( 

This has been a known issue for some time, and we've finally addressing it. The new images that are about to be published will fix this: https://github.com/decidim/docker/discussions/67

At this point I'm assuming you've moved on, but if you're still interested in Decidim, let us know and we'll help you get setup.
