### ISSUE TITLE
Add a README.md 

### ISSUE THREAD

**Issue by andreslucena** [decidim/docker#7]
Explaining what this repository works for, what commands it gives, Docker compatible versions, etc.

**Comment by mrcasals** [comment]
@josepjaume can you take a look at this, please?

**Comment by andreslucena** [comment]
@josepjaume / @jsperezg  could we tackle this? I think that we just a couple lines explaining how this works could be useful.

**Comment by jsperezg** [comment]
@andreslucena I'm a newbie for this repo but I will do my best to add as much information as I can.

**Comment by andreslucena** [comment]
I added some instructions to the README, but it'd be nice if anyone else can review it :)
