### ISSUE TITLE
I can't generate a new project

### ISSUE THREAD

**Issue by carlesaguilar** [decidim/docker#89]
Hello, i'm trying to generate a new decidim project using this commands but i can't do it.

```
APP_NAME=HelloWorld
IMAGE=ghcr.io/decidim/decidim-generator:latest
docker run -it -v "$(pwd):/code" ${IMAGE} ${APP_NAME}
```
and the response is:

```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "HelloWorld": executable file not found in $PATH: unknown.
ERRO[0001] error waiting for container: context canceled
```

Can you help me to solve it? Thanks!

**Comment by andreslucena** [comment]
I can confirm that this is also happening in my machine. 
I think there's a missing `decidim` here, please try it like this: 

```bash
APP_NAME=HelloWorld
IMAGE=ghcr.io/decidim/decidim-generator:latest
docker run -it -v "$(pwd):/code" ${IMAGE} decidim ${APP_NAME}
```

**Comment by carlesaguilar** [comment]
Thanks for help, now the command works but it shows another error when creates a Decidim project:

`Could not find gem 'decidim-dev (= 0.24.0.rc1)' in any of the gem sources listed in your Gemfile`

**Comment by andreslucena** [comment]
Oh, I cannot reproduce the last one actually... 

Which docker version are you using? (`docker --version`) What is your Operating System?

**Comment by carlesaguilar** [comment]
`Docker version 20.10.7, build 20.10.7-0ubuntu5~20.04.2`

**Comment by carlesaguilar** [comment]
Hello again, finally i generate a decidim project using a Debian distribution, the project it seems generated correctly but when i start the generated project executing `docker-compose up` i get this error: 

`error: database is uninitialized and superuser password is not specified. You must specify POSTGRES_PASSWORD to a non-empty value for the superuser.`

More info on this screenshot: https://drive.google.com/file/d/1s-KrYTSiDxpJ6zHiGJOqGxATx8QcKOFy/view?usp=sharing

can you help me? thanks.
