### ISSUE TITLE
Can't pull images

### ISSUE THREAD

**Issue by ztarbug** [decidim/docker#92]
Tried to pull decidim images but it appears they are not accessible. See below result of docker pull. 

docker pull ghcr.io/decidim/decidim:latest
Error response from daemon: Head "https://ghcr.io/v2/decidim/decidim/manifests/latest": denied: denied

docker pull ghcr.io/decidim/decidim:f0390f5165bb72ce737b787b5f70801be7fe66e7
Error response from daemon: Head "https://ghcr.io/v2/decidim/decidim/manifests/f0390f5165bb72ce737b787b5f70801be7fe66e7": denied: denied

**Comment by CristianCantoro** [comment]
@ztarbug wrote:
> docker pull ghcr.io/decidim/decidim:latest Error response from daemon: Head "https://ghcr.io/v2/decidim/decidim/manifests/latest": denied: denied

I am having the same issue with docker compose, following the instructions from the README:
```
$ git clone git@github.com:decidim/docker.git decidim-docker
Cloning into 'decidim-docker'...
remote: Enumerating objects: 788, done.
remote: Counting objects: 100% (121/121), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 788 (delta 53), reused 106 (delta 52), pack-reused 667
Receiving objects: 100% (788/788), 182.09 KiB | 900.00 KiB/s, done.
Resolving deltas: 100% (419/419), done.
$ cd decidim-docker 
$ ls
docker-compose.yml  Dockerfile  Dockerfile-dev  Dockerfile-generator  Dockerfile-test  README.md  scripts
$ docker compose up
[+] Running 0/9
 ⠋ pg Pulling                                                                  4.0s
 ⠋ redis Pulling                                                               4.0s
   ⠼ 025c56f98b67 Pulling fs layer                                             0.3s
   ⠼ 060e65aed679 Pulling fs layer                                             0.3s
   ⠼ b95291e865b7 Pulling fs layer                                             0.3s
   ⠼ 5d91e1f209b7 Waiting                                                      0.3s
   ⠼ 3b64ec7ffb7e Waiting                                                      0.3s
   ⠼ 0fb27e19f260 Waiting                                                      0.3s
Error response from daemon: Head "https://ghcr.io/v2/decidim/decidim/manifests/latest": denied: denied
```

**Comment by CristianCantoro** [comment]
A temporary workaround for the docker compose is to change [docker-compose.yml#L4](https://github.com/decidim/docker/blob/master/docker-compose.yml#L4) from:
```
ghcr.io/decidim/decidim:latest
```
to:
```
 image: decidim/decidim:latest
```
which pulls the image from [the mirror on Docker Hub](https://hub.docker.com/r/decidim/decidim).
