### ISSUE TITLE
Broken built and push images action

### ISSUE THREAD

**Issue by andreslucena** [decidim/docker#93]
There's a problem with the process where the images are built and pushed to Docker Hub, making that this doesn't work

The problem is here: 

> 
> Setting up nodejs (12.22.5~dfsg-2~11u1) ...
> update-alternatives: using /usr/bin/nodejs to provide /usr/bin/js (js) in auto mode
> Processing triggers for libc-bin (2.31-13+deb11u2) ...
> Removing intermediate container c06f45b52d74
>  ---> ff28ca9dbfbf
> Step 10/13 : RUN npm install -g npm@6.3.0
>  ---> Running in d49dfe4473a9
> /bin/sh: 1: npm: not found
> The command '/bin/sh -c npm install -g npm@6.3.0' returned a non-zero code: 127
> 
> Error: Process completed with exit code 127.

More information at https://github.com/decidim/docker/runs/5750825419?check_suite_focus=true

**Comment by ahukkanen** [comment]
I tested building the generator image, then building the Decidim image and finally running it with `docker compose` and it worked for me. So I believe #94 fixed this issue.
